port: 2424
admin_port: 2525
log:
  level: "info"

rate_limiter:
    enabled: true
    num_requests: 100

request_limits:
  max_size_bytes: 10240 # 10K
  max_num_values: 10

backend:
  type: "memory" # Can also be "memory", "memcache" or "cassandra"
  memcache:
    hosts: "10.0.0.1:11211" # single instance
    #hosts: ["10.0.0.1:11211", "10.0.0.2:11211"] # mutiple instances (use YAML array)
  cassandra:
    hosts: "127.0.0.1"
    keyspace: "prebid"
  azure:
      account: "azure-account-here"
      key: "azure-key-here"

compression:
  type: "none" # Can also be "snappy"

metrics:
  host: "default-metrics-host"
  database: "default-metrics-database"
  username: "metrics-username"
  password: "metrics-password"
