port: 2424
admin_port: 2525
log:
  level: "trace"
rate_limiter:
  enabled: true
  num_requests: 100
request_limits:
  allow_setting_keys: true
  max_size_bytes: 10240 # 10K
  max_num_values: 10
  max_ttl_seconds: 3600
backend:
  type: "aerospike" # Can also be "aerospike", "azure", "cassandra", "memcache" or "redis"
  aerospike:
    host: "aerospike-bids.prod.lax1.adnxs.net" # "01-aerospike-rc.envnxs.net"
    port: 3000
    namespace: "prebid"
    default_ttl_seconds: 3600
  azure:
    account: "azure-account-here"
    key: "azure-key-here"
  cassandra:
    hosts: "127.0.0.1"
    keyspace: "prebid"
  memcache:
    config_host: "" # Configuration endpoint for auto discovery. Replaced at docker build.
    poll_interval_seconds: 30 # Node change polling interval when auto discovery is used
    hosts: "10.0.0.1:11211" # List of nodes when not using auto discovery. Can also use an array for multiple hosts. 
  redis:
    host: "127.0.0.1"
    port: 6379
    password: ""
    db: 1
    expiration: 10 # in Minutes
    tls:
      enabled: false
      insecure_skip_verify: false
compression:
  type: "snappy" # Can also be "none"
metrics:
  type: "none" # Can also be "influx"
  influx:
    host: "http://influx.prebid.com"
    database: "some-database"
    username: "influx-username"
    password: "influx-password"
routes:
  allow_public_write: true
