port: 2424
admin_port: 2525
log:
  level: "info"
rate_limiter:
  enabled: true
  num_requests: 100
request_limits:
  allow_setting_keys: false
  max_size_bytes: 10240 # 10K
  max_num_values: 10
  max_ttl_seconds: 3600
backend:
  type: "memory" # Can also be "aerospike", "azure", "cassandra", or "memcache"
  aerospike:
    host: "aerospike.prebid.com"
    port: 3000
    namespace: "whatever"
  azure:
    account: "azure-account-here"
    key: "azure-key-here"
  cassandra:
    hosts: "127.0.0.1"
    keyspace: "prebid"
  memcache:
    hosts: "10.0.0.1:11211" # Can also use an array for multiple hosts
  redis:
    host: "127.0.0.1"
    port: 6379
    password: ""
    db: 1
    expiration: 10 # in Minutes
compression:
  type: "snappy" # Can also be "none"
metrics:
  type: "none" # Can also be "influx"
  influx:
    host: "http://influx.prebid.com"
    database: "some-database"
    username: "influx-username"
    password: "influx-password"
