port: 2424
admin_port: 2525
log:
  level: "info"
rate_limiter:
  enabled: true
  num_requests: 500
request_limits:
  allow_setting_keys: false
  max_size_bytes: 10240 # 10K
  max_num_values: 10
  max_ttl_seconds: 3600
backend:
  type: "redis" # Can also be "aerospike", "azure", "cassandra", or "memcache"
  redis:
    host: "localhost"
    port: 6379
    password: ""
    db: 0
    expiration: 10 # in Minutes
compression:
  type: "snappy" # Can also be "none"
metrics:
  type: "none" # Can also be "influx"
  influx:
    host: "http://influx.prebid.com"
    database: "some-database"
    username: "influx-username"
    password: "influx-password"
