port: 2424
admin_port: 2525
log:
  level: "info"
rate_limiter:
  enabled: true
  num_requests: 100
request_limits:
  allow_setting_keys: true
  max_size_bytes: 10240 # 10K
  max_num_values: 10
  max_ttl_seconds: 3600
backend:
  type: "redis" # Can also be "aerospike", "azure", "cassandra", "memcache" or "redis"
  redis:
    host: "<<REDIS_HOSTNAME>>"
    port: <<REDIS_PORT>>
    password: "<<REDIS_PASSWORD>>"
    db: 1
    expiration: 10 # in Minutes
compression:
  type: "snappy" # Can also be "none"
metrics:
  type: "none" # Can also be "influx"
  # graphite:
  #   host: stunnel:2003
  #   prefix: scrungus.pippins
  #   interval_sec: 10
