name: Package

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  Package:
    name: Package and Publish Docker Image
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:

    - name: Get Version
      id: get_version
      run: |
        echo ::set-output name=version::${GITHUB_REF/refs\/tags\/}
  
    - name: Checkout Branch
      uses: actions/checkout@v2

    - name: Build
      run: |
        docker build --build-arg DEPLOY_VERSION=${{ steps.get_version.outputs.version }} -t docker.io/prebid/prebid-cache:${{ steps.get_version.outputs.version }} .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Publish to Docker Hub
      run: |
        docker push docker.io/prebid/prebid-cache:${{ steps.get_version.outputs.version }}
